### ISSUE TITLE
Fails to find active connection

### ISSUE THREAD

**Issue by MCMic** [dlenski/wifi2qr#1]
Hello,

I’m not sure why, but my connection does not appear as "yes" when asking field "active" to nmcli.
However it does appear green, showing it is active.

So, instead of `conn="$(nmcli -t -f type,active,name conn | grep '^802-11-wireless:yes:' | cut -c21- | head -n1)"`
What would work for me is `conn="$(nmcli -t -f type,active,name connection show --active| grep '^802-11-wireless:' | cut -d":" -f3 | head -n1)"` because the `--active` option does list only my active connection.

Note: I found this after reading https://shibumi.dev/posts/share-your-wifi-via-qr-code/ and thinking «There must be a script for this!».
I packaged your script for archlinux: https://aur.archlinux.org/packages/wifi2qr-git

**Comment by dlenski** [comment]
> I’m not sure why, but my connection does not appear as "yes" when asking field "active" to nmcli.
However it does appear green, showing it is active.

Thanks, that's interesting. :thinking: 

What version of NetworkManager / nmcli are you using?

**Comment by MCMic** [comment]
```
$ nmcli -v
outil nmcli, version 1.22.10-1
```

Your commit does fix the problem.

**Comment by dlenski** [comment]
Aha, thanks. Is it possible that your `nmcli` isn't handling the `active` field correctly because some of its strings are in French. (J'ai été surpris de lire `outil nmcli` là où mon `nmcli` affiche `nmcli tool` :sweat_smile:)

Does `nmcli` show `oui`/`non` or `yes`/`no` for binary fields? There might be a bug in the handling of those when translated.

**Comment by MCMic** [comment]
No it says "no" for all connections for active fields.
